# Generated by Django 5.2 on 2025-05-06 12:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('tipo_vehiculo', models.CharField(choices=[('TAXI', 'Taxi'), ('MOTOCICLETA', 'Motocicleta'), ('CAMION', 'Camión'), ('FURGONETA', 'Furgoneta'), ('OTRO', 'Otro')], default='TAXI', max_length=20)),
                ('disponibilidad', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('NO_DISPONIBLE', 'No disponible')], default='DISPONIBLE', max_length=20)),
                ('ultima_disponibilidad', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
