# Generated by Django 5.2 on 2025-05-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
