# Generated by Django 5.2 on 2025-05-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='municipio_id',
            field=models.CharField(blank=True, default='0803', max_length=4, null=True),
        ),
    ]
