# Generated by Django 5.2 on 2025-05-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_municipio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto_vehiculo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_photos/'),
        ),
    ]
