# Generated by Django 5.2 on 2025-05-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_foto_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='capacidad_pasajeros',
            field=models.IntegerField(default=4),
        ),
    ]
