# Generated by Django 5.2 on 2025-05-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_capacidad_pasajeros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('TAXI', 'Taxi'), ('MOTOCICLETA', 'Motocicleta'), ('CAMION', 'Camión'), ('FURGONETA', 'Furgoneta'), ('COCHE', 'Coche'), ('OTRO', 'Otro')], default='TAXI', max_length=20),
        ),
    ]
