# Generated by Django 5.2 on 2025-05-10 23:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_tipo_vehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='capacidad_pasajeros',
        ),
        migrations.AddField(
            model_name='profile',
            name='dias_licencia',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='fecha_ultima_licencia',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
