# Generated by Django 5.2 on 2025-05-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_capacidad_pasajeros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='capacidad_pasajeros',
            field=models.IntegerField(default=4),
        ),
    ]
